[Icon Theme]
Name=Hicolor
Comment=SmartSort Fallback Icon Theme
Hidden=true
Directories=16x16/apps,22x22/apps,24x24/apps,32x32/apps,scalable/apps

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[22x22/apps]
Size=22
Context=Applications
Type=Fixed

[24x24/apps]
Size=24
Context=Applications
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Fixed

[scalable/apps]
Size=128
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable
